name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
