name: Continuous Integration

on: 
  pull_request: {}
  push:
    branches: 
      - master
      - Develop   
    paths-ignore:
      - 'Documentation/**'
      - '*.md'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          
jobs:
  buildAndTestForSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - UnityProject
        unityVersion:
          - 2019.3.0f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - WebGL # WebGL.
          # Not yet supported GitHub actions:
          # - Android # Build a Android standalone.
          # - PS4 # Build a Playstation 4 standalone.
          # - Windows Store # Build a standalone for Windows Store devices.
          
    steps:

      #Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
            
      # Run Tests
      - uses: webbertakken/unity-test-runner@v1.4
        id: testRunner
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
          
      # Build
      - uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: "-myParameter myValue -myBoolean -ThirdParameter andItsValue"
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
   
#enable this job to request a manual unity license
#Request-License:
# runs-on: ubuntu-latest
#if: false
#steps:
#  - name: Checkout repository
#    uses: actions/checkout@v2
#
#      - name: Request manual activation file
#       uses: MirrorNG/unity-runner@master
#      id: getManualLicenseFile
#     with:
#        entrypoint: /request_activation.sh

      # This will produce a Unity_xxx.alf file
      # download it in your computer and upload it to
      # https://license.unity3d.com/manual
      # That will produce a Unity_xxx.ulf file
      # add the contents of Unity_xxx.ulf file to your repository's secrets
      # as UNITY_LICENSE
      # then disable this job
#    - name: Expose as artifact
#      uses: actions/upload-artifact@v1
#     with:
#        name: Manual Activation File
#       path: ${{ steps.getManualLicenseFile.outputs.filePath }}
  
        
  Zenject-usage:
    runs-on: [windows-latest]
    name: Zenject-usage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - name: MSBuild
        working-directory: AssemblyBuild\Zenject-usage
        run: msbuild Zenject-usage.sln
        
      - name: Upload dll
        uses: actions/upload-artifact@v1
        with:
          name: Zenject-usage
          path: AssemblyBuild\Zenject-usage\bin\Debug\
        
  buildUnity:
    name: Unity test
    runs-on: ubuntu-latest
    needs: Zenject-usage
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
  
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Zenject-usage
        uses: actions/download-artifact@v1
        with:
          name: Zenject-usage

      - name: Install Zenject-usage
        run: |
          ls -l Zenject-usage
          cp Zenject-usage/Zenject-usage.dll UnityProject/Assets/Plugins/Zenject/Source/Usage
          ls -l UnityProject/Assets/Plugins/Zenject/Source/Usage
                
# Upload artifacts
#      - name: Publish test results
#        uses: actions/upload-artifact@v1
#        with:
#          name: Test results (editor mode)
#          path: UnityProject/Tests/editmode-results.xml

#      - name: Release
#        uses: cycjimmy/semantic-release-action@v2
#        with:
#          extra_plugins: |
#            @semantic-release/exec
#            @semantic-release/changelog
#            @semantic-release/git
#          branch: master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
